/**
 * CONCEPT PRICES — review and confirm final rates before launch.
 * This seed data serves as an internal reference and fallback when Supabase is not configured.
 */
import type { BillingType, Category, Product } from "@/types";

export const CONCEPT_PRICE_DISCLAIMER =
  "Concept prices — final rates will be confirmed before launch.";

export const categories: Category[] = [
  { id: "cat-websites", slug: "websites", name: "Websites", description: "Professional websites and landing pages", sortOrder: 1 },
  { id: "cat-webshops", slug: "webshops", name: "Online stores", description: "Complete e-commerce solutions", sortOrder: 2 },
  { id: "cat-ai", slug: "ai-automatisering", name: "AI & automation", description: "Smart automations and AI integrations", sortOrder: 3 },
  { id: "cat-whatsapp", slug: "whatsapp-oplossingen", name: "WhatsApp solutions", description: "WhatsApp Business AI and automation", sortOrder: 4 },
  { id: "cat-reviewflows", slug: "reviewflows", name: "Review flows", description: "Automated review and feedback flows", sortOrder: 5 },
  { id: "cat-onderhoud", slug: "onderhoud", name: "Maintenance", description: "Ongoing maintenance and management", sortOrder: 6 },
  { id: "cat-hosting", slug: "hosting", name: "Hosting", description: "Reliable hosting and infrastructure", sortOrder: 7 },
  { id: "cat-templates", slug: "templates", name: "Templates", description: "Professional templates", sortOrder: 8 },
  { id: "cat-support", slug: "support", name: "Support", description: "Support hours and remote assistance", sortOrder: 9 },
  { id: "cat-maatwerk", slug: "maatwerk", name: "Custom work", description: "Fully bespoke solutions", sortOrder: 10 },
];

function product(
  partial: Omit<Product, "status" | "featured" | "sortOrder" | "seoTitle" | "seoDescription"> & {
    sortOrder: number;
    featured?: boolean;
  },
): Product {
  return {
    ...partial,
    status: "PUBLISHED",
    featured: partial.featured ?? false,
    seoTitle: `${partial.name} | VDB Digital`,
    seoDescription: partial.shortDescription,
    targetAudience: partial.targetAudience ?? "SMEs looking to grow professionally online.",
    workflow: partial.workflow ?? "Intake → design → build → delivery → aftercare.",
    requiredInput: partial.requiredInput ?? ["Company name", "Target audience", "Required functionality"],
  };
}

export const seedProducts: Product[] = [
  product({
    id: "prod-starter-website",
    slug: "starter-website",
    name: "Starter Website",
    shortDescription: "A professional website for businesses that want to go online quickly with a solid foundation.",
    fullDescription: "The Starter Website is ideal for entrepreneurs who need a reliable online presence without unnecessary complexity. We build a conversion-focused website with clear structure, mobile optimisation and a solid technical foundation.",
    categorySlug: "websites",
    categoryName: "Websites",
    priceCents: 149900,
    fromPriceCents: null,
    billingType: "ONE_TIME" as BillingType,
    deliveryTime: "2–3 weeks",
    includedItems: ["Up to 5 pages", "Responsive design", "Contact form", "Basic SEO", "SSL certificate"],
    excludedItems: ["Online store", "Custom integrations", "Copywriting"],
    extensions: ["Extra pages", "Blog module", "Multilingual setup"],
    faqs: [
      { question: "Can I expand later?", answer: "Yes — the website is built to grow into a larger platform or online store.", sortOrder: 1 },
    ],
    sortOrder: 1,
    featured: true,
  }),
  product({
    id: "prod-business-website",
    slug: "business-website",
    name: "Business Website",
    shortDescription: "Extended business website with more pages, integrations and conversion optimisation.",
    fullDescription: "The Business Website is designed for growing companies that need more than an online business card. More pages, advanced forms, integrations and a strong focus on conversion.",
    categorySlug: "websites",
    categoryName: "Websites",
    priceCents: 299900,
    fromPriceCents: null,
    billingType: "ONE_TIME",
    deliveryTime: "3–5 weeks",
    includedItems: ["Up to 12 pages", "Advanced forms", "Analytics integration", "Conversion optimisation", "Training"],
    excludedItems: ["Online store", "Full copywriting"],
    extensions: ["CRM integration", "Lead nurturing", "A/B testing"],
    faqs: [],
    sortOrder: 2,
    featured: true,
  }),
  product({
    id: "prod-premium-website",
    slug: "premium-website",
    name: "Premium Website",
    shortDescription: "Premium business website with bespoke design, advanced functionality and strategic guidance.",
    fullDescription: "For companies that want maximum online impact. Premium design, custom components, advanced animations and strategic guidance from concept to launch.",
    categorySlug: "websites",
    categoryName: "Websites",
    priceCents: null,
    fromPriceCents: 499900,
    billingType: "ONE_TIME",
    deliveryTime: "5–8 weeks",
    includedItems: ["Bespoke design", "Unlimited pages", "Advanced animations", "Strategy sessions", "Premium support"],
    excludedItems: ["Ongoing ad management"],
    extensions: ["Marketing automation", "Personalisation"],
    faqs: [],
    sortOrder: 3,
    featured: true,
  }),
  product({
    id: "prod-landingspagina",
    slug: "conversiegerichte-landingspagina",
    name: "Conversion-focused Landing Page",
    shortDescription: "One powerful page focused on leads, enquiries or campaigns.",
    fullDescription: "A targeted landing page that turns visitors into leads. Ideal for campaigns, product launches or specific services.",
    categorySlug: "websites",
    categoryName: "Websites",
    priceCents: 79900,
    fromPriceCents: null,
    billingType: "ONE_TIME",
    deliveryTime: "1–2 weeks",
    includedItems: ["Conversion-focused design", "Form or CTA flow", "Mobile optimisation", "Basic tracking"],
    excludedItems: ["Multiple pages", "CMS"],
    extensions: ["A/B variant", "Ad platform integration"],
    faqs: [],
    sortOrder: 4,
  }),
  product({
    id: "prod-complete-webshop",
    slug: "complete-webshop",
    name: "Complete Online Store",
    shortDescription: "Full online store with product management, payments and order flow.",
    fullDescription: "A professional online store that builds trust. Product catalogue, cart, checkout, Mollie payments and an admin environment for day-to-day management.",
    categorySlug: "webshops",
    categoryName: "Online stores",
    priceCents: null,
    fromPriceCents: 599900,
    billingType: "ONE_TIME",
    deliveryTime: "6–10 weeks",
    includedItems: ["Product catalogue", "Cart & checkout", "Mollie integration", "Order management", "Responsive design"],
    excludedItems: ["ERP stock sync", "Marketplace features"],
    extensions: ["Subscriptions", "Wholesale", "ERP integration"],
    faqs: [],
    sortOrder: 5,
    featured: true,
  }),
  product({
    id: "prod-website-redesign",
    slug: "website-redesign",
    name: "Website Redesign",
    shortDescription: "Modernise your existing website with better UX, speed and conversion.",
    fullDescription: "We analyse your current website, identify improvements and deliver a redesign that fits your brand and goals.",
    categorySlug: "websites",
    categoryName: "Websites",
    priceCents: null,
    fromPriceCents: 249900,
    billingType: "ONE_TIME",
    deliveryTime: "3–6 weeks",
    includedItems: ["UX analysis", "New design", "Technical migration", "Performance optimisation"],
    excludedItems: ["New functionality outside scope"],
    extensions: ["Extra pages", "New integrations"],
    faqs: [],
    sortOrder: 6,
  }),
  product({
    id: "prod-whatsapp-starter",
    slug: "whatsapp-ai-starter",
    name: "WhatsApp AI Starter",
    shortDescription: "Automated WhatsApp replies for FAQs and lead capture.",
    fullDescription: "Let WhatsApp work for you. Automatic answers to FAQs, lead capture outside office hours and handoff to a team member when needed.",
    categorySlug: "whatsapp-oplossingen",
    categoryName: "WhatsApp solutions",
    priceCents: 19900,
    fromPriceCents: null,
    billingType: "MONTHLY",
    deliveryTime: "1–2 weeks",
    includedItems: ["WhatsApp Business connection", "Basic AI responses", "FAQ setup", "Lead notifications"],
    excludedItems: ["Complex workflows", "CRM integration"],
    extensions: ["CRM integration", "Appointment scheduling"],
    faqs: [],
    sortOrder: 7,
    featured: true,
  }),
  product({
    id: "prod-whatsapp-business",
    slug: "whatsapp-ai-business",
    name: "WhatsApp AI Business",
    shortDescription: "Advanced WhatsApp automation with workflows, scheduling and follow-up.",
    fullDescription: "Full WhatsApp Business AI solution with advanced workflows, appointment scheduling, lead scoring and integration with your existing systems.",
    categorySlug: "whatsapp-oplossingen",
    categoryName: "WhatsApp solutions",
    priceCents: 49900,
    fromPriceCents: null,
    billingType: "MONTHLY",
    deliveryTime: "2–4 weeks",
    includedItems: ["Advanced AI workflows", "Appointment scheduling", "Lead scoring", "Reporting", "Monthly optimisation"],
    excludedItems: ["Custom AI training on proprietary data"],
    extensions: ["Custom training", "Multi-channel"],
    faqs: [],
    sortOrder: 8,
  }),
  product({
    id: "prod-reviewflow",
    slug: "reviewflow-setup",
    name: "Review Flow Setup",
    shortDescription: "Automated review and feedback flows after appointments or purchases.",
    fullDescription: "Collect reviews at the right moment. Automatic invitations after appointments, deliveries or service — fully configured and tested.",
    categorySlug: "reviewflows",
    categoryName: "Review flows",
    priceCents: 39900,
    fromPriceCents: null,
    billingType: "ONE_TIME",
    deliveryTime: "1–2 weeks",
    includedItems: ["Flow design", "Email/WhatsApp triggers", "Review platform integration", "Testing & handover"],
    excludedItems: ["Review ad management"],
    extensions: ["Multi-location setup", "Dashboard reporting"],
    faqs: [],
    sortOrder: 9,
  }),
  product({
    id: "prod-afspraken",
    slug: "afsprakenautomatisering",
    name: "Appointment Automation",
    shortDescription: "Schedule, confirm and remind for appointments online — automatically.",
    fullDescription: "Let customers book appointments online. Automatic confirmations, reminders and calendar synchronisation.",
    categorySlug: "ai-automatisering",
    categoryName: "AI & automation",
    priceCents: null,
    fromPriceCents: 149900,
    billingType: "ONE_TIME",
    deliveryTime: "2–3 weeks",
    includedItems: ["Booking system", "Calendar sync", "Automatic reminders", "Confirmation emails"],
    excludedItems: ["Complex resource planning"],
    extensions: ["WhatsApp reminders", "Payment at booking"],
    faqs: [],
    sortOrder: 10,
  }),
  product({
    id: "prod-websitebeheer",
    slug: "maandelijks-websitebeheer",
    name: "Monthly Website Management",
    shortDescription: "Ongoing management, updates and small changes for your website.",
    fullDescription: "Focus on your business — we take care of your website. Monthly updates, security patches, small content changes and performance monitoring.",
    categorySlug: "onderhoud",
    categoryName: "Maintenance",
    priceCents: 14900,
    fromPriceCents: null,
    billingType: "MONTHLY",
    deliveryTime: "Active immediately after agreement",
    includedItems: ["Monthly updates", "Security monitoring", "Small content changes", "Backup checks", "Monthly report"],
    excludedItems: ["Major redesigns", "New features"],
    extensions: ["Extra change hours", "Priority support"],
    faqs: [],
    sortOrder: 12,
  }),
  product({
    id: "prod-technisch-onderhoud",
    slug: "technisch-onderhoud",
    name: "Technical Maintenance",
    shortDescription: "Technical maintenance, monitoring and incident response for existing systems.",
    fullDescription: "Proactive technical maintenance for websites, online stores and integrations. Monitoring, patches, incident response and technical optimisation.",
    categorySlug: "onderhoud",
    categoryName: "Maintenance",
    priceCents: 9900,
    fromPriceCents: null,
    billingType: "MONTHLY",
    deliveryTime: "Active immediately after agreement",
    includedItems: ["Uptime monitoring", "Security patches", "Performance checks", "Incident response"],
    excludedItems: ["Feature development"],
    extensions: ["SLA upgrade", "24/7 monitoring"],
    faqs: [],
    sortOrder: 13,
  }),
  product({
    id: "prod-conversie-audit",
    slug: "conversie-audit",
    name: "Conversion Audit",
    shortDescription: "In-depth analysis of your website or store with actionable recommendations.",
    fullDescription: "We analyse your website or online store for conversion, UX, speed and technical quality. You receive a report with prioritised improvements.",
    categorySlug: "support",
    categoryName: "Support",
    priceCents: 79900,
    fromPriceCents: null,
    billingType: "ONE_TIME",
    deliveryTime: "1–2 weeks",
    includedItems: ["UX analysis", "Conversion analysis", "Technical scan", "Priority list", "Presentation"],
    excludedItems: ["Implementation of improvements"],
    extensions: ["Implementation package", "Follow-up session"],
    faqs: [],
    sortOrder: 14,
  }),
  product({
    id: "prod-support-uren",
    slug: "supporturen-bundel",
    name: "Support Hours Bundle",
    shortDescription: "Flexible bundle of support hours for changes, help and optimisation.",
    fullDescription: "A bundle of support hours to use when you need them. For content changes, technical help, small adjustments or advice.",
    categorySlug: "support",
    categoryName: "Support",
    priceCents: 49900,
    fromPriceCents: null,
    billingType: "ONE_TIME",
    deliveryTime: "Available immediately",
    includedItems: ["10 support hours", "Valid for 6 months", "Priority over ad-hoc requests", "Ticketing system"],
    excludedItems: ["New feature development"],
    extensions: ["Extra hours bundle"],
    faqs: [],
    sortOrder: 15,
  }),
  product({
    id: "prod-maatwerk",
    slug: "maatwerk-digitalisering",
    name: "Custom Digitalisation",
    shortDescription: "Fully bespoke digitalisation solution for unique business processes.",
    fullDescription: "When standard solutions are not enough, we build custom. From internal portals to complex integrations — fully aligned with your processes.",
    categorySlug: "maatwerk",
    categoryName: "Custom work",
    priceCents: null,
    fromPriceCents: null,
    billingType: "QUOTE_ONLY",
    deliveryTime: "By agreement",
    includedItems: ["Intake & analysis", "Technical design", "Build", "Testing & handover", "Documentation"],
    excludedItems: ["Scope outside agreement"],
    extensions: ["Ongoing maintenance", "Training"],
    faqs: [],
    sortOrder: 16,
  }),
];

export function getSeedProductBySlug(slug: string): Product | undefined {
  return seedProducts.find((p) => p.slug === slug);
}

export function getSeedProductsByCategory(categorySlug: string): Product[] {
  return seedProducts.filter((p) => p.categorySlug === categorySlug);
}

export function getFeaturedProducts(): Product[] {
  return seedProducts.filter((p) => p.featured);
}
